[package]
name = "qinpel-stp"
version = "0.1.0"
edition = "2018"

[dependencies]
url = "2.2"
reqwest = { version = "0.11", features = ["blocking"] }
sha2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple-error = "0.2"